!!python/object/new:moveit_msgs.msg._RobotTrajectory.RobotTrajectory {state: [!!python/object/new:trajectory_msgs.msg._JointTrajectory.JointTrajectory {
      state: [!!python/object/new:std_msgs.msg._Header.Header {state: [0, !!python/object/new:genpy.rostime.Time {
              state: [0, 0]}, world]}, [ur5_shoulder_pan_joint, ur5_shoulder_lift_joint,
          ur5_elbow_joint, ur5_wrist_1_joint, ur5_wrist_2_joint, ur5_wrist_3_joint],
        [!!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.9919276281590017, -2.0431083553267717, 0.14178222325532897,
                -1.2756139006668494, 2.1141834045235246, -4.2468020846619936e-05],
              !!python/tuple [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], !!python/tuple [-0.49929978350328796,
                0.0, 0.0, 0.0, 0.0, 0.0], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [0, 0]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.9595767576376762, -1.9790737653953774, 0.16313174820041543,
                -1.307334362827393, 2.1088997191898486, -0.003445592437995053], !!python/tuple [
                -0.15325807813270775, 0.3033556138908954, 0.10114062185663261, -0.15027159980135893,
                -0.02503077804856624, -0.016121863165161357], !!python/tuple [-0.49785057484461315,
                0.985434298785533, 0.32854983792675035, -0.48814916156749194, -0.08131112821013652,
                -0.052371000224808804], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [0, 359979107]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.9272258871163509, -1.915039175463983, 0.1844812731455019,
                -1.3390548249879366, 2.1036160338561722, -0.006848716855143486], !!python/tuple [
                -0.16820298650135715, 0.33293723143401177, 0.11100331454084295, -0.16492528277066382,
                -0.027471645694106456, -0.017693981063746825], !!python/tuple [0.4619704543036294,
                -0.914413990258864, -0.30487123156537055, 0.4529682224584268, 0.07545103036368543,
                0.04859661912360293], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [0, 509304087]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.8948750165950254, -1.8510045855325887, 0.20583079809058835,
                -1.3707752871484802, 2.0983323485224963, -0.01025184127229192], !!python/tuple [
                -0.17827917979722796, 0.14286747782979073, -0.055391355315823655,
                -0.08826280288399868, -0.06965511073714743, 0.003993785063263485],
              !!python/tuple [-0.435204216589871, -0.7003943100827665, -0.9996831159806688,
                0.2168715427177857, -0.37254946580502535, 0.12338855860646268], !!python/tuple [],
              !!python/object/new:genpy.rostime.Duration {state: [0, 779438181]}]},
          !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.8314756540564382, -1.837969275725143, 0.1550106572771035,
                -1.3865985635761886, 2.0662710036532936, -0.004740408439039608], !!python/tuple [
                -0.34005843021412024, 0.06991816341649815, -0.27258660996434836, -0.08487212374691602,
                -0.17196908880808978, 0.029561956500203414], !!python/tuple [-1.0055732261306205,
                0.20675221345809938, -0.806054996517117, -0.25097197334882604, -0.508522936245424,
                0.08741648295537029], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [1, 47172204]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.768076291517851, -1.824933965917697, 0.10419051646361865,
                -1.4024218400038968, 2.034209658784091, 0.0007710243942127028], !!python/tuple [
                -0.5047333773046873, 0.10377637376591178, -0.40458800027016084, -0.1259718620439108,
                -0.25524595561846075, 0.04387747756962487], !!python/tuple [-0.9634131174102821,
                0.19808382852990997, -0.772259977512379, -0.24044961117053149, -0.487202378257425,
                0.08375142075047222], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [1, 190183533]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.7046769289792636, -1.8118986561102515, 0.053370375650133806,
                -1.418245116431605, 2.0021483139148883, 0.006282457227465014], !!python/tuple [
                -0.611991693178326, 0.12582936169598447, -0.49056493281105107, -0.15274149999107683,
                -0.30948697189400326, 0.05320165655305749], !!python/tuple [-0.8800564581554949,
                0.18094517232913065, -0.705442315765532, -0.2196453726314718, -0.4450485380214678,
                0.07650506037252142], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [1, 302166925]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.6412775664406763, -1.7988633463028056, 0.002550234836648957,
                -1.4340683928593134, 1.970086969045686, 0.011793890060717325], !!python/tuple [
                -0.6991293172810067, 0.143745408176293, -0.5604133689740405, -0.17448939552537868,
                -0.35355286318334556, 0.060776703734309684], !!python/tuple [-0.9075880433413199,
                0.186605840323503, -0.7275112921706064, -0.2265167332484114, -0.4589713853829617,
                0.07889843589663892], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [1, 398542898]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.577878203902089, -1.7858280364953598, -0.04826990597683589,
                -1.4498916692870218, 1.9380256241764833, 0.017305322893969636], !!python/tuple [
                -0.7750774469412836, 0.15936082384888955, -0.6212924455027189, -0.19344460582501666,
                -0.39196017643869585, 0.06737902588193362], !!python/tuple [-0.8455823402487651,
                0.17385707571013914, -0.677808291442745, -0.21104128774164485, -0.4276148204096049,
                0.07350815665424038], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [1, 484168542]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.5144788413635017, -1.7727927266879142, -0.09909004679032074,
                -1.46571494571473, 1.9059642793072809, 0.022816755727221947], !!python/tuple [
                -0.8056660698413026, 0.16565003812674922, -0.6458119053336191, -0.20107894497780152,
                -0.40742898162225916, 0.07003815578205733], !!python/tuple [0.10328337173234113,
                -0.021235714281307466, 0.0827906667347758, 0.02577756740550448, 0.05223086901460844,
                -0.00897862917388503], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [1, 562465464]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.45107947882491445, -1.7597574168804684, -0.1499101876038056,
                -1.4815382221424385, 1.8739029344380782, 0.028328188560474258], !!python/tuple [
                -0.7672694939927289, 0.1577554593535553, -0.6150336874896699, -0.19149588910465049,
                -0.3880116592583591, 0.06670026498406245], !!python/tuple [0.8293358768588643,
                -0.1705167001120094, 0.6647853283696572, 0.2069864791301085, 0.4193989102680752,
                -0.07209581924001215], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [1, 641556269]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.38768011628632726, -1.7467221070730226, -0.20073032841729044,
                -1.4973614985701467, 1.8418415895688756, 0.033839621393726566], !!python/tuple [
                -0.6933742004797199, 0.14256211977276773, -0.5558001388952456, -0.17305302770756092,
                -0.350642474543141, 0.06027639997055326], !!python/tuple [0.862544314972949,
                -0.17734456496278717, 0.6914047995059514, 0.2152746743889902, 0.4361925678745907,
                -0.07498269489356049], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [1, 728056718]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.3242807537477399, -1.7336867972655767, -0.2515504692307753,
                -1.513184774997855, 1.809780244699673, 0.03935105422697888], !!python/tuple [
                -0.6054062200443246, 0.12447534678017175, -0.48528609941915846, -0.15109789100773513,
                -0.3061566682943807, 0.05262916825980141], !!python/tuple [0.9185447569505707,
                -0.1888586099200629, 0.7362940575830652, 0.22925132080951285, 0.4645122450949865,
                -0.07985092482890353], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [1, 825025574]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.26088139120915255, -1.720651487458131, -0.30237061004426014,
                -1.5290080514255633, 1.7777188998304703, 0.04486248706023119], !!python/tuple [
                -0.4963578370742078, 0.10205430973659986, -0.3978742713483141, -0.12388148632100665,
                -0.2510104069781746, 0.043149375179093855], !!python/tuple [0.9353822470333227,
                -0.19232050434329892, 0.7497907803053109, 0.233453638455285, 0.4730270401127858,
                -0.08131464137045533], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [1, 938848315]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.1974820286705654, -1.7076161776506853, -0.353190750857745,
                -1.5448313278532715, 1.7456575549612678, 0.0503739198934835], !!python/tuple [
                -0.3373115509043501, 0.0693533876620926, -0.27038474565955845, -0.08418655485644672,
                -0.17057997949628786, 0.0293231648119174], !!python/tuple [0.957981233377998,
                -0.19696699882747948, 0.7679058468027121, 0.23909391611107675, 0.48445544989292255,
                -0.08327921625498277], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [2, 84354866]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.1340826661319781, -1.6945808678432395, -0.40401089167122983,
                -1.56065460428098, 1.7135962100920652, 0.05588535272673582], !!python/tuple [
                -0.11904225813436975, -0.0909629105551236, -0.19051175120237035, 0.01786399644085196,
                -0.08249283029557132, 0.02284494078908991], !!python/tuple [0.8568252119670424,
                -1.0013469971565692, 0.0071063519938120235, 0.5539202416006933, 0.27394846479434415,
                0.014840855628033753], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [2, 349726018]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.13432502310912664, -1.7625573845000309, -0.4597690436551259,
                -1.5326001327384315, 1.7006013052647868, 0.06321741586525037], !!python/tuple [
                0.0012147649812478786, -0.34071844332039636, -0.27947637920745244,
                0.14061732407405508, -0.06513431346006818, 0.03675047298311296], !!python/tuple [
                0.0035136215402976428, -0.985503928831927, -0.808365602520872, 0.40672563535546613,
                -0.1883963814553647, 0.1062981362509687], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [2, 643936955]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.13456738008627517, -1.8305339011568222, -0.5155271956390219,
                -1.5045456611958832, 1.6876064004375084, 0.07054947900376493], !!python/tuple [
                0.0018400532305402192, -0.5160998892907995, -0.4233340789031632, 0.2129986996880715,
                -0.09866155655730763, 0.05566741516288711], !!python/tuple [0.0034997283891304693,
                -0.9816071645104628, -0.8051692578423284, 0.405117408439155, -0.18765144652808102,
                0.10587782459856171], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [2, 794865072]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.13480973706342367, -1.8985104178136136, -0.5712853476229179,
                -1.4764911896533348, 1.6746114956102303, 0.07788154214227949], !!python/tuple [
                0.0022483146480066734, -0.630609441981441, -0.5172612372300494, 0.2602577406820257,
                -0.12055206834304832, 0.06801861101085727], !!python/tuple [0.003208755143763409,
                -0.8999947104629059, -0.7382261451268184, 0.37143527257515807, -0.1720497928213845,
                0.09707496597332242], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [2, 911701400]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.1350520940405722, -1.9664869344704052, -0.6270434996068139,
                -1.4484367181107864, 1.6616165907829519, 0.08521360528079405], !!python/tuple [
                0.0025674855544859116, -0.7201308029750826, -0.5906916790588164, 0.29720394796014454,
                -0.13766564849300506, 0.07767453784166459], !!python/tuple [0.0030662945740278945,
                -0.8600372336641714, -0.7054507813128365, 0.3549444908921143, -0.1644112194775933,
                0.09276508430899812], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [3, 11753806]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.13529445101772072, -2.0344634511271966, -0.68280165159071,
                -1.420382246568238, 1.6486216859556735, 0.09254566841930861], !!python/tuple [
                0.0028365104688838237, -0.7955871681675478, -0.6525852223804945, 0.3283454149565222,
                -0.15209045771409507, 0.08581339021309889], !!python/tuple [0.0028932782649931424,
                -0.8115094538933246, -0.6656455742651057, 0.334916674175959, -0.15513428222607856,
                0.08753079513456855], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [3, 101096376]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.13553680799486925, -2.102439967783988, -0.738559803574606,
                -1.3923277750256897, 1.635626781128395, 0.09987773155782316], !!python/tuple [
                0.0028335581281603416, -0.7947590928188306, -0.6519059885300598, 0.32800366140032033,
                -0.1519321565701761, 0.08572407259226675], !!python/tuple [-0.0029588858248852904,
                0.8299111250161954, 0.6807396571291642, -0.3425111962880348, 0.15865208479474976,
                -0.08951563079786487], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [3, 182964048]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.13577916497201778, -2.1704164844407794, -0.794317955558502,
                -1.3642733034831414, 1.6226318763011167, 0.10720979469633772], !!python/tuple [
                0.0025609975541026364, -0.7183110424247066, -0.589199009379162, 0.2964529177060863,
                -0.1373177693087869, 0.0774782553619416], !!python/tuple [-0.0030707048931567344,
                0.8612742441899505, 0.706465446733946, -0.3554550153835046, 0.16464769576150887,
                -0.09289851037617447], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [3, 272501514]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.1360215219491663, -2.238393001097571, -0.8500761075423982,
                -1.336218831940593, 1.6096369714738383, 0.11454185783485228], !!python/tuple [
                0.0022171125001258247, -0.6218578337129042, -0.5100826772222717, 0.2566458794511716,
                -0.1188790447441864, 0.06707464760195793], !!python/tuple [-0.0035958473057179662,
                1.0085666901286392, 0.8272829730010789, -0.4162438279948142, 0.1928052332595741,
                -0.10878572505799255], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [3, 372846854]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.1362638789263148, -2.306369517754362, -0.9058342595262943,
                -1.3081643603980446, 1.5966420666465602, 0.12187392097336686], !!python/tuple [
                0.0017970745204427144, -0.5040451795927157, -0.41344612982125983,
                0.20802362113431055, -0.09635708711769245, 0.054367173594625076],
              !!python/tuple [-0.003240901730848333, 0.9090112159434015, 0.7456219886868134,
                -0.37515645907980805, 0.17377345617388323, -0.09804750164775003],
              !!python/tuple [], !!python/object/new:genpy.rostime.Duration {state: [
                  3, 492885220]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.13650623590346334, -2.3743460344111535, -0.9615924115101901,
                -1.2801098888554963, 1.5836471618192818, 0.1292059841118814], !!python/tuple [
                0.0011137667722503825, -0.3123903691011141, -0.25624010371977557,
                0.128926093173646, -0.059718904631777286, 0.03369495853513105], !!python/tuple [
                -0.003512922976130837, 0.9853079948865565, 0.8082048865083079, -0.40664477179309255,
                0.1883589252411051, -0.10627700248111492], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [3, 646747711]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [0.13674859288061186, -2.442322551067945, -1.0173505634940863,
                -1.252055417312948, 1.5706522569920034, 0.13653804725039595], !!python/tuple [
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0], !!python/tuple [-0.003512176759557635,
                0.9850986953486821, 0.8080332072870627, -0.4065583921399719, 0.18831891395913833,
                -0.10625442707563691], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [4, 18244085]}]}]]}, !!python/object/new:trajectory_msgs.msg._MultiDOFJointTrajectory.MultiDOFJointTrajectory {
      state: [!!python/object/new:std_msgs.msg._Header.Header {state: [0, !!python/object/new:genpy.rostime.Time {
              state: [0, 0]}, '']}, [], []]}]}
